exports.preguntas =[
'¿Alguna vez te ha gustado alguien? ¿Cuánto tiempo?',
'¿Cuál es tu mayor miedo?',
'¿Alguna vez te ha gustado alguien y has sentido a esa persona como tú también?',
'Cual es el nombre de la ex novia de tu amigo que una vez te gustó en secreto?',
'¿Alguna vez ha robado el dinero de su madre o su padre? ¿La razón?',
'que te hace feliz cuando estas triste',
'¿Alguna vez amor no correspondido? si alguna vez con quien? ¿cómo se siente brou?',
'¿Alguna vez ha tenido una aventura con alguien?',
'quién es la persona que tiene más influencia en tu vida?',
'algo orgulloso de lo que obtuviste este año',
'quién es la persona que puede hacerte sentir incómodo',
'¿Quién es la persona que alguna vez te hizo sentir incómodo?',
'(para los musulmanes) ¿nunca has rezado en todo el día?',
'¿Quién está más cerca de su tipo de pareja ideal aquí?',
'¿Con quién te gusta jugar?',
'¿Alguna vez has rechazado a alguien? ¿la razón por la cual?',
'di eventos que te hacen daño y que aún recuerdas',
'¿Qué logros has obtenido este año?',
'¿Cuál fue tu peor hábito en la escuela?',
'¿Te gusta alguien del grupo?',
'¿Odias el anime?',
'¿Te masturbas?',
'¿Odias a alguien del grupo?',
'¿Abusas de alguien o alguien abusa de ti?',
'¿Cual es gu juego favorito?'
]