exports.preguntas =[
'Te reto a poner en tu info de Whatsapp que te gusta Anuel por 24 horas',
'Te reto a decirle a tu crush que la amas y pasar screenshot en el grupo',
'Te reto a poner en tu estado que buscas pareja',
'Te reto a poner en tu perfil la foto de tu crush',
'Te reto a decirle a alguien que te gusta...',
'Te reto a mandar un audio cantando',
'Te reto mandar audio hablando con vos de niña de 5 años',
'Te reto a poner en tu info que te gusta tu vecin@',
'Te reto mandar una foto tuya sin taparte la cara',
'Te reto a decir que apodo tenias cuando eras un/a niñ@ aun',
'Te reto a enviar un vídeo bailando',
'Te reto a enviar el último meme que allas visto',
'Te reto a enviar tu canción favorita',
'Te reto a envía un mensaje a tu ex diciéndole "Aún me gustas y te extraño"',
'Dile "gay" a un miembro del grupo',
'Dile "ERES TAN HERMOSO Y ME GUSTAS" a los chicos',
'Te reto a enviar un screenshot de tus llamadas recientes de whatsapp',
'suelta el emoji "🦄" cada vez que escribes durante 1 día',
'envía una nota de voz que diga ¿puedo llamarte bebé?',
'manda foto en calzones',
'Escribe en ingles por un dia',
'Cambia tu nombre a "Soy gay" durante 5 horas',
'Publica en tu estado, "soy gay"',
'Dile a tu ex "te amo vuelve conmigo"',
'Manda una nota de voz haciendo gemidos',
'Dile a alguien de tu sexo opuesto que lo amas',
'Dile al siguiente que mande mensaje que lo amas',
'Manda fotos de tu crush',
'Borra tu whatsapp',
'Toma foto de cara y mandala',
'envía tu foto con el texto "soy un niño gay y fuí adoptado"',
'Manda un audio gritando',
'Sal afuera de tu casa y grita',
'Cambia tu nombre a "3cm" por un dia',
'Finge ser un bot durante 2 horas'
]