exports.preguntas =[
'Con quien de los que están aqui en el grupo te besarías? (etiqueta)',
'¿Alguna vez te ha gustado alguien? ¿Cuanto tiempo?',
'Alguna vez te llegó a gustar el/la herman@ de tu mejor amig@?',
'Cuantos años tienes?',
'Cuanto tiempo ah pasado desde que diste tu último beso?',
'Te gustan los chicos o las chicas o ambos?',
'Que opinas sobre BTS?',
'Que opinas sobre los administradores?',
'Tienes novi@?',
'Cuantas veces te as sentido ignorad@ por tu pareja o insuficiente para el/ella?',
'Que opinas de la nueva política de Whatsapp?',
'Que opinas sobre Telegram?',
'Que opinas sobre Discord?', 
'Tienes canal de Youtube?',
'Como se llama tu mamá?',
'Como se llama tu papá?',
'Que tipo de música te gusta?',
'Soy un bot genial?',
'Cual es tu nombre completo?',
'Te gusta el anime?',
'Sobre el anime, cual es tu personaje favorito?',
'Eres gay?',
'Que opinas sobre Este bot?',
'Que opinas sobre el grupo?',
'Que tal te parece esta función de verdad o reto?',
'Cual es tu youtuber favorito?',
'Me odias?'
]